// src/app/layout.tsx

// Hapus baris ini jika ada: "use client";

import Script from 'next/script';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import PrelineScriptWrapper from './components/PrelineScriptWrapper';
import Navbar from './components/navbar'; // Pastikan komponen ini memiliki "use client" jika perlu
import Footer from './components/footer';

// Ekspor metadata hanya boleh ada di Server Component
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Konten head */}
      </head>
      <body className="flex flex-col min-h-screen">
        <Navbar />
        <main className='flex-grow mt-4'>{children}</main>
        <PrelineScriptWrapper />
        <Script src="/path/ke/preline.js" strategy="afterInteractive" />
        <Footer />
      </body>
    </html>
  );
}